name: mirror_scorpion_key_generator
description: "Mirror Scorpion Key Generator - Developer Tool"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # UI & Design
  cupertino_icons: ^1.0.6
    
  # Utilities
  intl: ^0.20.2
  shared_preferences: ^2.2.0
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
